---
- name: make sure needed software is installed
  dnf: name=dnf-utils
- name: remove old kernel packages for RPM based systems
  shell:  package-cleanup -y --oldkernels --count='{{ package_cleanup_keep_old_kernels }}'
...
