---
- name: make sure needed software is installed
  dnf: name=dnf-utils
- name: remove old kernel packages for RPM based systems
  shell:  dnf remove $(dnf repoquery --installonly --latest-limit '{{ ospatch_keep_kernel_nr }}' -q)
...
