---
- name: Check for reboot hint.
  shell: if [ $(readlink -f /vmlinuz) != /boot/vmlinuz-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  changed_when: false
  register: reboot_hint

- name: reboot {{ inventory_hostname }} if needed
  shell: sleep 5 && shutdown -r now "Ansible reboot triggered"
  async: 1            # fire and forget # fire and forget # fire and forget 
  poll: 0             # do not poll for updates on this task
  ignore_errors: true # due rebooting can break the return_code
  when: reboot_hint.stdout.find("reboot") != -1 and ospatch_reboot == true
...
