---
- name: Check for reboot hint.
  shell: if [ $(readlink -f /vmlinuz) != /boot/vmlinuz-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  changed_when: false
  register: reboot_hint

- name: reboot {{ inventory_hostname }} if needed
  block:
  - name: reboot host {{ inventory_nodename }}
    shell: sleep 5 ; shutdown -r now "Ansible reboot"
    async: 10 # do not care for 10 sec (we left in 5 sec)
    poll: 0  # fire and forget

  - name: wait for {{ inventory_nodename }} to finish reboot
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 10  # do not check for at least 10 sec
    connection: local

  - name: confirm {{ inventory_nodename }} has booted within 300 sec
    shell: test $(cat /proc/uptime | cut -d. -f1) -lt 300
  when: reboot_hint.stdout.find("reboot") != -1 and ospatch_reboot == true
...
