---
- name: install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - yum-plugin-security
  - yum-utils
- name: install security patches with yum
  yum:
    name: '*'
    state: latest
    security: yes
- name: install all kernel updates with yum
  yum:
    name: 'kernel*'
    state: latest
...
